[tools]
bun = "latest"
go = "latest"
node = "24.17.0"
# node = "24"
python = "3.14"
ruby = "latest"
rust = "latest"
terraform = "latest"
uv = "latest"

[settings]
experimental = true
minimum_release_age = "12h"
idiomatic_version_file_enable_tools = ["ruby", "bun"]

[settings.ruby]
compile = false

[settings.python]
compile = false
